### ISSUE TITLE
DAG Task generates duplicated output names

### ISSUE THREAD

**Issue by AntoineDao** [pollination/annual-radiation#8]
The current iteration of this recipe generates duplicated task output names. This shouldn't be possible in theory so we should add some more validation on Queenbee's end to make sure it doesn't happen again. I noticed this as I was able to create and translate a job to send to Argo but then Argo throws an error :upside_down_face: 

https://github.com/pollination/annual-radiation/blob/88a57f79ca8cb3c2829b6d3bfee229df322f26fa/pollination/annual_radiation/entry.py#L69-L87

This code generates this yaml definition (`sensor-grids-file` is duplicated):

```yaml
- type: DAGTask
  annotations: {}
  name: create-rad-folder
  template: honeybee-radiance/create-radiance-folder
  needs: []
  arguments:
  - type: TaskPathArgument
    annotations: {}
    name: input-model
    from:
      type: InputFileReference
      annotations: {}
      variable: model
    sub_path: null
  - type: TaskArgument
    annotations: {}
    name: sensor-grid
    from:
      type: InputReference
      annotations: {}
      variable: sensor-grid
  loop: null
  sub_folder: null
  returns:
  - type: TaskPathReturn
    annotations: {}
    name: model-folder
    description: null
    path: model
    required: true
  - type: TaskPathReturn
    annotations: {}
    name: sensor-grids-file
    description: null
    path: results/direct/grids_info.json
    required: true
  - type: TaskPathReturn
    annotations: {}
    name: sensor-grids-file
    description: null
    path: results/total/grids_info.json
    required: true
  - type: TaskReturn
    annotations: {}
    name: sensor-grids
    description: Sensor grids information.
```
